<a href="https://colab.research.google.com/github/ayannazm17/ayannazm.github.io/blob/main/maths/simple_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create Database

In [1]:
import sqlite3
import pandas as pd

# Create or connect to a database file
conn = sqlite3.connect("shop.db")
cur = conn.cursor()

print("Database connected successfully.")

Database connected successfully.

Create simple Table

In [2]:
cur.execute("""
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT,
    category TEXT,
    price REAL,
    quantity INTEGER
);
""")

conn.commit()
print("Table created.")

Table created.

Insert sample data

In [3]:
cur.executemany("""
INSERT INTO sales (product_name, category, price, quantity)
VALUES (?, ?, ?, ?);
""", [
    ('Laptop', 'Electronics', 800, 2),
    ('Phone', 'Electronics', 500, 3),
    ('Headphones', 'Electronics', 100, 5),
    ('Desk Chair', 'Furniture', 150, 4),
    ('Desk', 'Furniture', 300, 2),
    ('Notebook', 'Stationery', 5, 20),
    ('Pen Pack', 'Stationery', 10, 10)
])

conn.commit()
print("Data inserted.")

Data inserted.

View all data

In [4]:
df = pd.read_sql_query("SELECT * FROM sales ", conn)
df

   sale_id product_name     category  price  quantity
0        1       Laptop  Electronics  800.0         2
1        2        Phone  Electronics  500.0         3
2        3   Headphones  Electronics  100.0         5
3        4   Desk Chair    Furniture  150.0         4
4        5         Desk    Furniture  300.0         2
5        6     Notebook   Stationery    5.0        20
6        7     Pen Pack   Stationery   10.0        10

Calculate the AVG Price

In [5]:
pd.read_sql_query("""
SELECT AVG(price) FROM sales
""", conn)

   AVG(price)
0  266.428571

Calculate Total Quantity Sold

In [6]:
pd.read_sql_query("""
SELECT SUM(quantity) FROM sales
""", conn)

   SUM(quantity)
0             46

Calculate Highest and Lowest Price

In [7]:
pd.read_sql_query("""
SELECT MAX(price), MIN(price) FROM sales
""", conn)

   MAX(price)  MIN(price)
0       800.0         5.0

Calculate revenue per product

In [8]:
pd.read_sql_query("""
SELECT product_name, price * quantity AS revenue FROM sales
""", conn)

  product_name  revenue
0       Laptop   1600.0
1        Phone   1500.0
2   Headphones    500.0
3   Desk Chair    600.0
4         Desk    600.0
5     Notebook    100.0
6     Pen Pack    100.0

Calculate total revenue

In [16]:
pd.read_sql_query("""
SELECT SUM(price * quantity) FROM sales
""", conn)

   SUM(price * quantity)
0                 5000.0

Calculate revenue per category

In [12]:
pd.read_sql_query("""
SELECT category, SUM(price * quantity) AS revenue FROM sales
GROUP BY category
""", conn)

      category  revenue
0  Electronics   3600.0
1    Furniture   1200.0
2   Stationery    200.0

Calculate average price per category

In [13]:
pd.read_sql_query("""
SELECT category, AVG(price) AS average_price FROM sales
GROUP BY category
""", conn)

      category  average_price
0  Electronics     466.666667
1    Furniture     225.000000
2   Stationery       7.500000

Calculate count products per category

In [14]:
pd.read_sql_query("""
SELECT category, COUNT(*) AS product_count FROM sales
GROUP BY category
""", conn)

      category  product_count
0  Electronics              3
1    Furniture              2
2   Stationery              2

Which category has a revenue greater than 2000

In [15]:

pd.read_sql_query("""
SELECT category, SUM(price * quantity) AS revenue FROM sales
GROUP BY category
HAVING revenue > 2000
""", conn)

      category  revenue
0  Electronics   3600.0